name: CDN CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Copy assets to one folder."
        run: cd .. && ls  && pwd #bash build.sh
      #- name: "Deploy"
        #uses: JamesIves/github-pages-deploy-action@v4.2.5
        #with:
          #branch: gh-pages
          #folder: cdn
