name: CDN CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: "Clone repository"
        uses: actions/checkout@v2
        
      - name: "Copy assets to one folder."
        run: bash build.sh
        
      - name: "Deploy"
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: cdn
