name: LUME CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copy assets to one folder.
        run: mkdir cdn && mv -f apis cdn && mv -f audio cdn && mv -f css cdn && mv -f fonts cdn && mv -f images cdn && mv -f models cdn && mv -f index.html cdn
        
      - name: "Deploy"
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: cdn
